# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 09:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='课程名称')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='英文名称')),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='作业标题')),
                ('content', models.TextField(null=True, verbose_name='详细(以md形式保存)')),
                ('courser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission_system.Courser', verbose_name='课程')),
            ],
        ),
        migrations.CreateModel(
            name='HomeworkAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True, verbose_name='详细')),
                ('code', models.TextField(null=True, verbose_name='代码')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission_system.Homework', verbose_name='所属作业')),
            ],
        ),
    ]
