# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 03:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission_system', '0002_auto_20161011_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='部门')),
            ],
        ),
        migrations.AlterField(
            model_name='homeworkanswer',
            name='code',
            field=models.TextField(blank=True, null=True, verbose_name='代码'),
        ),
        migrations.AlterField(
            model_name='homeworkanswer',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='详细'),
        ),
        migrations.AlterField(
            model_name='homeworkanswer',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='courser',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='submission_system.Part', verbose_name='所属部门'),
        ),
    ]
